// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function get_key_name(key){
    switch (key) {
        case 1: return "Left Click"; break;
        case 2: return "Right Click"; break;
        case 8: return "Backspace"; break;
        case 9: return "Tab"; break;
        case 13: return "Enter"; break;
        case 16: return "Shift"; break;
        case 19: return "Pause"; break;
        case 20: return "Capslock"; break;
        case 27: return "Escape"; break;
        case 32: return "Space"; break;
        case 33: return "Page Up"; break;
        case 34: return "Page Down"; break;
        case 35: return "End"; break;
        case 36: return "Home"; break;
        case 37: return "Left"; break;
        case 38: return "Up"; break;
        case 39: return "Right"; break;
        case 40: return "Down"; break;
        case 45: return "Insert"; break;
        case 46: return "Delete"; break;
        case 48: return "0"; break;
        case 49: return "1"; break;
        case 50: return "2"; break;
        case 51: return "3"; break;
        case 52: return "4"; break;
        case 53: return "5"; break;
        case 54: return "6"; break;
        case 55: return "7"; break;
        case 56: return "8"; break;
        case 57: return "9"; break;
        case 65: return "A"; break;
        case 66: return "B"; break;
        case 67: return "C"; break;
        case 68: return "D"; break;
        case 69: return "E"; break;
        case 70: return "F"; break;
        case 71: return "G"; break;
        case 72: return "H"; break;
        case 73: return "I"; break;
        case 74: return "J"; break;
        case 75: return "K"; break;
        case 76: return "L"; break;
        case 77: return "M"; break;
        case 78: return "N"; break;
        case 79: return "O"; break;
        case 80: return "P"; break;
        case 81: return "Q"; break;
        case 82: return "R"; break;
        case 83: return "S"; break;
        case 84: return "T"; break;
        case 85: return "U"; break;
        case 86: return "V"; break;
        case 87: return "W"; break;
        case 88: return "X"; break;
        case 89: return "Y"; break;
        case 90: return "Z"; break;    
        case 91: return "Windows"; break;
        case 92: return "Windows"; break;
        case 93: return "What is this key called?"; break;
        case 96: return "Num 0"; break;
        case 97: return "Num 1"; break;
        case 98: return "Num 2"; break;
        case 99: return "Num 3"; break;
        case 100: return "Num 4"; break;
        case 101: return "Num 5"; break;
        case 102: return "Num 6"; break;
        case 103: return "Num 7"; break;
        case 104: return "Num 8"; break;
        case 105: return "Num 9"; break;
        case 106: return "*"; break;
        case 107: return "+"; break;
        case 109: return "-"; break;
        case 110: return "."; break;
        case 111: return "/"; break;
        case 112: return "F1"; break;
        case 113: return "F2"; break;
        case 114: return "F3"; break;
        case 115: return "F4"; break;
        case 116: return "F5"; break;
        case 117: return "F6"; break;
        case 118: return "F7"; break;
        case 119: return "F8"; break;
        case 120: return "F9"; break;
        case 121: return "F10"; break;
        case 122: return "F11"; break;
        case 123: return "F12"; break;
        case 144: return "Num Lock"; break;
        case 145: return "Scrl Lock"; break;
		case 160: return "Left Shift"; break;
		case 161: return "Right Shift"; break;
        case 162: return "Control"; break;
        case 163: return "Control"; break;
        case 164: return "Alt"; break;
        case 165: return "Alt"; break;
        case 186: return ";"; break;
        case 188: return ","; break;
        case 190: return "."; break;
        case 191: return "/"; break;
        case 192: return "`"; break;
        case 219: return "["; break;
        case 220: return "\\"; break;
        case 221: return "]"; break;
        case 222: return "'"; break;
        default: return string(key); break;
    }
}